woolenwires/guestbook/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.GuestBookEntryView.as_view(), name='index'),
    path('sign-guestbook', views.GuestBookEntryAddView.as_view(), name='add_entry')
]

woolenwires/urls.py
from django.contrib import admin
from django.urls import path
from .guestbook.views import GuestBookEntryView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('/', GuestBookEntryView.as_view(), 'index')
]

woolenwires/woolenwires/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('guestbook.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

woolenwires/guestbook/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse
# Create your models here.


class Guest(models.Model):

    guest_name = models.CharField(max_length = 100)
    email = models.EmailField(unique=True)


class GuestBookEntry(models.Model):
    
    knit_message = models.CharField(max_length = 140)
    extra_message = models.TextField()
    email = models.EmailField()
    name = models.CharField(max_length=250)
    date = models.DateTimeField(default=datetime.now())

    def get_absolute_url(self):
        return reverse('index')

woolenwires/guestbook/forms.py
from django import forms
from .models import Guest, GuestBookEntry

class GuestBookEntryForm(forms.Form):

    class Meta:
        model = GuestBookEntry

woolenwires/guestbook/views.py
from django.forms import fields
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from .models import GuestBookEntry

# Create your views here.

class GuestBookEntryView(ListView):
    
    queryset = GuestBookEntry.objects.all()

class GuestBookEntryAddView(CreateView):
    model = GuestBookEntry
    fields = ['knit_message', 'extra_message', 'email', 'name']
    

woolenwires/guestbook/templates/guestbook/guestbookentry_form.html
{% include 'guestbook/header.html' %}
<body>
    <div class="bg">
      <div class="section" style="background-color: rgba(46, 46, 46, 0.863);">
           
              <form method="post">{% csrf_token %} 
                  {{ form.as_p }}
                  <div align="center">
                     <button type="submit" align="center" class="button-56" role="button">Sign Guestbook</button> 
                  </div>
              </form>
          

            
      </div>
    </div>
    
    </body> 
</html>

woolenwires/guestbook/templates/guestbook/guestbookentry_list.html
{% include 'guestbook/header.html' %}
<body>
<div class="bg">
  <div class="section" align="center">
    <h1>Welcome to Jacky and Stephen's Wedding Guestbook!</h1>
    <p>Please sign the guestbook to leave a memory for us. There will be two spaces for messages: 
      a knit message that will be knitted into a wedding blanket in wool and a second space to leave
      a longer message. </p>
    <p>These messages will rendered into our wedding quilt thorugh our hacked knitting machine that 
     takes input through the computer to create new stitches. 
    </p>
    <p>The 'knitting' below are the messages we have received from others who have signed the guestbook
      so far. The stitches are a likeness of the final quilt.</p>
    <div align="center">
      <a href="{% url 'add_entry' %}"> <button align="center" class="button-56" role="button">Sign Guestbook</button></a>
    </div>
  </div>
  <div class="section">

          {% for note in object_list %}
          <div class="knit">
            {{ note.knit_message }}
          </div>
          {% empty %}
            no notes yet
          {% endfor %}

          
  </div>
</div>

</body>
</html>

woolenwires/guestbook/templates/guestbook/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">


  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Woolen Wires</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" type="text/css" href="{% static "custom.css" %}">
  <!-- <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/skeleton.css"> -->
  <style>

    html, body {
  height: 100%;
  margin: 0%;
  color: #000;
}

* {
  margin: 0;
  border: 0;
  padding: 0;
}

.bg {
  background-image: url("{% static 'bg-opt2.png' %}");
  height: 100%;
  position: top;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  margin: 0;
  border: 0;
  padding: 0;
}

.caption {
  position: absolute;
  left: 0;
  top: 50%;
  width: 100%;
  text-align: center;
  color: #000;
}

h1, h2, h3 {
  letter-spacing: 5px;
  color: rgb(224, 220, 0);
}

p {
    padding: 5px;
    font-size: 16pt;
    color: rgb(131, 129, 0);
    text-align: left;
    margin-left: 10px;
    margin-right: 10px;
}

h1 {
    font-family: 'Sofia';
}

.section {
    background-color: rgba(46, 46, 46, 0.863);
    text-align: center;
    max-width: 40%;
    top: 20%;
    position: relative;
    margin-bottom: 20px; 
    border-radius: 25px;
    padding: 2px;
}

h3 {
  letter-spacing: 5px;
  text-transform: uppercase;
  font: 20px "Lato", sans-serif;
  color: #111;
}

@font-face {
    font-family: 'knitfont';
    src:  url('{% static "knitfont.ttf" %}') format('truetype');
    font-weight: normal;
    font-style: normal;
}

.knit {
  font-family: 'knitfont';
  font-size: 40px;
  color: rgb(226, 226, 226);
  background-color: rgba(46, 46, 46, 0.863);
}

/* CSS */
.button-56 {
  align-items: center;
  background-color: #f1b9519c;
  border: 2px solid rgb(201, 147, 0);
  border-radius: 8px;
  box-sizing: border-box;
  color: #111;
  cursor: pointer;
  display: flex;
  font-family: 'Sofia';
  font-size: 16px;
  height: 48px;
  justify-content: center;
  line-height: 24px;
  max-width: 100%;
  padding: 0 25px;
  position: relative;
  text-align: center;
  text-decoration: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
}

.button-56:after {
  background-color: #111;
  border-radius: 8px;
  content: "";
  display: block;
  height: 48px;
  left: 0;
  width: 100%;
  position: absolute;
  top: -2px;
  transform: translate(8px, 8px);
  transition: transform .2s ease-out;
  z-index: -1;
}

.button-56:hover:after {
  transform: translate(0, 0);
}

.button-56:active {
  background-color: rgb(224, 220, 0);
  outline: 0;
}

.button-56:hover {
  outline: 0;
}

@media (min-width: 768px) {
  .button-56 {
    padding: 0 40px;
  }
}

#id_knit_message {
    font-size: 16pt;
    color: rgb(224, 220, 0);
    width: 90%;
    font-family: 'knitfont';
    background-color: rgba(46, 46, 46, 0.863);
}

#id_extra_message {
    font-size: 14pt;
    font-family: 'Raleway';
    width: 95%;
    height: 10%;
    color: rgb(224, 220, 0);
    background-color: rgba(46, 46, 46, 0.863);
}

#id_email {
    width: 40%;
    font-family: 'Raleway';
    color: rgb(224, 220, 0);
    background-color: rgba(46, 46, 46, 0.863);
}

#id_name {
    width: 40%;
    font-family: 'Raleway';
    color: rgb(224, 220, 0);
    background-color: rgba(46, 46, 46, 0.863);
}
  </style>

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <!-- <link rel="icon" type="image/png" href="images/favicon.png"> -->


</head>

woolenwires/woolenwires/templates/guestbook/guestbookentry_list.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">


  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Woolen Wires</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" type="text/css" href="css/custom.css">
  <!-- <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/skeleton.css"> -->
  

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <!-- <link rel="icon" type="image/png" href="images/favicon.png"> -->


</head>
<body>

<div class="bg">
  <div class="section" style="background-color: rgba(46, 46, 46, 0.863);">

            <h2>A Solstice Celebration</h1>
            <h1>With Jacky and Stephen</h1>
            <h2>Join us for a Solstice Elopment celebration!</h2>
            <p> A wintery celebration to welcome the light into our 
                lives as we join our communities even more 
                closely. Come celebrate with us, amplify our joy, as we
                bring the light into the darkness on the shortest day
                of the year. 
            </p>
            <h2>Event Info</h2>
            <p>Location: <b>Wonderbar, Beacon NY</b></p>
            <p>Time: <b>4pm - 7pm</b></p>
            <p>Fair: Cocktail Hour</p>

  </div>
</div>

</body>
</html>